import 'package:zamaan/core/utils/typedef.dart';
import 'package:zamaan/data/sources/base_data_source.dart';

/// Local data source contract for scheduled occurrence data operations.
///
/// Provides specialized data access methods for scheduled occurrences
/// targeting local storage (Hive, SQLite, etc.). Implements the data layer
/// for the repository pattern, focusing on device-local persistence.
///
/// ## Key Features:
/// - Date-based occurrence retrieval for calendar views
/// - Task-focused queries for scheduling history
/// - Scheduler management operations
/// - Bulk deletion for cleanup operations
abstract class ScheduledOccurrenceLocalDataSource<Model> extends BaseDataSource<Model> {
  /// Returns occurrences where startDateTime falls on specified date.
  EResultFuture<List<Model>> getByDate(DateTime date);

  /// Returns all occurrences (past, present, future) for a task.
  EResultFuture<List<Model>> getByTaskId(String taskId);

  /// Returns only future occurrences for a task.
  EResultFuture<List<Model>> getUpcomingByTaskId(String taskId);

  /// Returns occurrences generated by specific scheduler rules.
  EResultFuture<List<Model>> getBySchedulerIds(List<String> schedulerIds);

  /// Deletes all occurrences from specified schedulers. Irreversible.
  EResultFutureVoid deleteBySchedulerIds(List<String> schedulerIds);

  /// Deletes all occurrences from specified task. Irreversible.
  EResultFutureVoid deleteByTaskId(String future);
}
