import 'package:zamaan/core/utils/typedef.dart';
import 'package:zamaan/domain/entities/scheduled_occurrence.dart';
import 'package:zamaan/domain/repositories/bases/base_repository.dart';

/// Repository interface for managing scheduled task occurrences in the domain layer.
///
/// This abstract class defines the contract for accessing and manipulating
/// [ScheduledOccurrenceEntity] instances, providing specialized queries
/// for occurrence retrieval and management beyond basic CRUD operations.
///
/// ## Responsibilities:
/// - Retrieve occurrences by various criteria (date, task, scheduler, etc.)
/// - Manage occurrence lifecycle and cleanup operations
/// - Provide specialized queries for UI presentation and business logic
/// - Abstract data source implementation details from domain services
///
/// ## Available Methods:
///
/// **Retrieval Operations:**
/// - [get], [getById], [getByIds] - Basic entity retrieval
/// - [getByDate] - Date-based filtering
/// - [getByTaskId] - Task-based filtering
/// - [getUpcomingByTaskId] - Future task occurrences
/// - [getBySchedulerIds] - Scheduler-based filtering
/// - [exists] - Existence checking
///
/// **Creation Operations:**
/// - [create] - Single occurrence creation
/// - [createBatch] - Bulk occurrence creation
///
/// **Update Operations:**
/// - [update] - Single occurrence update
/// - [update] - Bulk occurrence update
///
/// **Deletion Operations:**
/// - [delete] - Single occurrence deletion
/// - [deleteBatch] - Bulk occurrence deletion
/// - [deleteBySchedulerIds] - Scheduler-based cleanup
/// - [deleteByTaskId] - Task-based cleanup
///
/// ## Typical Usage:
/// - Daily agenda and calendar views
/// - Task scheduling history and analytics
/// - Scheduler management and cleanup operations
/// - Upcoming task notifications and reminders
/// - Task deletion and cleanup workflows
abstract class ScheduledOccurrenceRepository extends BaseRepository<ScheduledOccurrenceEntity> {
  /// Retrieves occurrences for a specific calendar date.
  ///
  /// Returns occurrences where `startDateTime` falls on the specified date.
  /// Ideal for daily planning and calendar views.
  EResultFuture<List<ScheduledOccurrenceEntity>> getByDate(DateTime date);

  /// Retrieves all occurrences for a specific task.
  ///
  /// Returns complete history including past, present, and future instances.
  /// Useful for task analytics and scheduling pattern analysis.
  EResultFuture<List<ScheduledOccurrenceEntity>> getByTaskId(String taskId);

  /// Retrieves future occurrences for a specific task.
  ///
  /// Returns only occurrences where `startDateTime` is after current time.
  /// Perfect for upcoming deadlines and task reminders.
  EResultFuture<List<ScheduledOccurrenceEntity>> getUpcomingByTaskId(String taskId);

  /// Retrieves occurrences from specific schedulers.
  ///
  /// Useful for bulk operations on occurrences from particular scheduling rules.
  EResultFuture<List<ScheduledOccurrenceEntity>> getBySchedulerIds(List<String> schedulerIds);

  /// Deletes all occurrences generated by the specified schedulers.
  ///
  /// Used when removing scheduling rules from the system.
  /// Irreversible operation - use with caution.
  EResultFutureVoid deleteBySchedulerIds(List<String> schedulerIds);

  /// Deletes all occurrences associated with a specific task.
  ///
  /// Used when a task is permanently removed or schedule needs complete reset.
  /// Irreversible operation - use with caution.
  EResultFutureVoid deleteByTaskId(String taskId);
}
